distancia_em_metros = float(input('Digite a distância em metros: '))
distancia_em_km = float(distancia_em_metros/1000)
distancia_em_Hm = float(distancia_em_metros/100)
distancia_em_Dam = float(distancia_em_metros/10)
distancia_em_dm = float(distancia_em_metros*10)
distancia_em_cm = float(distancia_em_metros*100)
distancia_em_mm = float(distancia_em_metros*1000)
print('A distância de {}m corresponde a: '.format(distancia_em_metros))
print('{} Km'.format(distancia_em_km))
print('{} Hm'.format(distancia_em_Hm))
print('{} Dam'.format(distancia_em_Dam))
print('{} dm'.format(distancia_em_dm))
print('{} cm'.format(distancia_em_cm))
print('{} mm'.format(distancia_em_mm))
